import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  VendorStatus,
  LocationLockType,
  VendorLevel,
} from '@prisma/client';

// =========================================================================
// BEST SELLING FOODS
// =========================================================================

export class BestSellingFoodDto {
  @ApiProperty({ example: 'food-uuid-123' })
  id: string;

  @ApiProperty({ example: 'Jollof Rice & Chicken' })
  name: string;

  @ApiPropertyOptional({ example: 'Smokey party jollof with grilled chicken' })
  description?: string;

  @ApiProperty({ example: 3500.0 })
  price: number;

  @ApiPropertyOptional({ example: 'https://cdn.example.com/jollof.jpg' })
  imageUrl?: string;

  @ApiProperty({ example: true })
  isAvailable: boolean;

  @ApiProperty({ example: 340, description: 'Total quantity sold across all completed orders' })
  totalQuantitySold: number;

  @ApiProperty({ example: 1190000.0, description: 'Total revenue generated by this item' })
  totalRevenueGenerated: number;
}

// =========================================================================
// VENDOR SUMMARY SCHEMA (FOR LISTINGS & SEARCH)
// =========================================================================

export class VendorSummaryDto {
  @ApiProperty({ example: 'v123-uuid-890' })
  id: string;

  @ApiProperty({ example: 'Solohitech Food Ventures' })
  name: string;

  @ApiProperty({ enum: VendorStatus, example: VendorStatus.ACTIVE })
  status: VendorStatus;

  @ApiPropertyOptional({ example: 'Home of authentic local dishes and fast food.' })
  description?: string;

  @ApiPropertyOptional({ example: '123 Main Street, Garki' })
  address?: string;

  @ApiPropertyOptional({ example: 'Abuja' })
  city?: string;

  @ApiPropertyOptional({ example: 'FCT' })
  state?: string;

  @ApiPropertyOptional({ example: '+2348012345678' })
  phoneNumber?: string;

  @ApiPropertyOptional({ example: 'contact@solohitech.com' })
  email?: string;

  @ApiPropertyOptional({ example: 'https://cdn.example.com/logo.jpg' })
  logo?: string;

  @ApiPropertyOptional({ example: 'https://cdn.example.com/cover.jpg' })
  coverPhoto?: string;

  @ApiPropertyOptional({ example: 9.0765 })
  latitude?: number;

  @ApiPropertyOptional({ example: 7.3986 })
  longitude?: number;

  @ApiPropertyOptional({ example: '08:00 AM' })
  openingTime?: string;

  @ApiPropertyOptional({ example: '10:00 PM' })
  closingTime?: string;

  @ApiProperty({ example: 4.8 })
  averageRating: number;

  @ApiProperty({ example: 10 })
  deliveryRadiusKm: number;

  @ApiProperty({ enum: LocationLockType, example: LocationLockType.RADIUS })
  locationLockType: LocationLockType;

  @ApiProperty({ enum: VendorLevel, example: VendorLevel.LEVEL_1 })
  level: VendorLevel;
}

// =========================================================================
// MARKETPLACE SEARCH RESPONSE
// =========================================================================

export class SearchFoodResultDto {
  @ApiProperty({ example: 'food-123' })
  id: string;

  @ApiProperty({ example: 'Spicy Beef Burger' })
  name: string;

  @ApiPropertyOptional({ example: 'Double patty with cheddar cheese and house sauce' })
  description?: string;

  @ApiProperty({ example: 4500.0 })
  price: number;

  @ApiPropertyOptional({ example: 'https://cdn.example.com/burger.jpg' })
  imageUrl?: string;

  @ApiProperty({ example: 'v123-uuid-890' })
  vendorId: string;

  @ApiProperty({ example: 'Solohitech Food Ventures' })
  vendorName: string;
}

export class SearchMarketplaceResponseDto {
  @ApiProperty({ type: [VendorSummaryDto], description: 'Matching vendors found' })
  vendors: VendorSummaryDto[];

  @ApiProperty({ type: [SearchFoodResultDto], description: 'Matching food/menu items found' })
  foods: SearchFoodResultDto[];

  @ApiProperty({ example: 'Burger', description: 'Query string executed' })
  query: string;
}

// =========================================================================
// VENDOR FULL PROFILE RESPONSE (ME & ONBOARDING)
// =========================================================================

export class VendorFullProfileResponseDto extends VendorSummaryDto {
  @ApiProperty({ example: 'user-uuid-123' })
  userId: string;

  @ApiPropertyOptional({ example: '0123456789' })
  accountNumber?: string;

  @ApiPropertyOptional({ example: 'Solohitech Ventures Ltd' })
  accountName?: string;

  @ApiPropertyOptional({ example: 'GTBank' })
  bankName?: string;

  @ApiPropertyOptional({ example: '058' })
  bankCode?: string;

  @ApiPropertyOptional({ example: 'https://solohitech.com' })
  website?: string;

  @ApiPropertyOptional({ example: '@solohitech_foods' })
  instagram?: string;

  @ApiPropertyOptional({ example: 'solohitechfoods' })
  facebook?: string;

  @ApiPropertyOptional({ example: '@solohitech' })
  twitter?: string;

  @ApiPropertyOptional({ example: '@solohitech' })
  tiktok?: string;

  @ApiProperty({ example: '2026-07-29T12:00:00.000Z' })
  createdAt: Date;

  @ApiPropertyOptional({ example: '2026-07-29T12:00:00.000Z' })
  updatedAt?: Date;
}